#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#compton --config /home/alvaromr/.config/compton/compton.conf &
feh --bg-fill /home/alvaromr/Escritorio/wallpaper/aot.jpg &
#feh --bg-fill --conversion-timeout 1 /usr/share/desktop-base/homeworld-theme/wallpaper/contents/images/1920x1080.svg &
$HOME/.config/polybar/launch.sh &
WNAME L3GD &
killall mate-notification-daemon; dunst &


picom --experimental-backends &
bspc config pointer_modifier mod 1 
bspc monitor eDP-1 -d I II III IV V VI 
bspc monitor HDMI-1 -d VII VIII
#bspc monitor -d I II III IV V
# VIII IX X
bspc rule -a Xfce4-terminal state=floating

bspc config border_width         2
bspc config window_gap         5
bspc config normal_border_color \#00000
bspc config presel_feedback_color \#515151
bspc config focused_border_color \#ff5500
bspc config split ratio      1

~/.config/polybar/./launch.sh
if [[ $(xrander -q | grep 'HDMI-1 connected ') ]]; then 
	xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of eDP-1 & 
fi


